config/routes.rb
Checkbookproweb::Application.routes.draw do
  resources :categories

  resources :transactions

  resources :accounts

  match 'account/monthly/:id/:begin_date/:end_date', 
			  :controller => 'accounts', 
			  :action => 'show',
              :id => /\d+/,
              :begin_date => /[^\/]+/,
              :end_date => /[^\/]+/
			  
  match 'account/transactions/since/:date/:id',
             :controller => 'accounts',
             :action     => 'since',
             :date => /[^\/]+/,
             :id => /\d+/
			 
  match 'transactions/new/:id',
             :controller => 'transactions',
             :action     => 'new',
             :id => /\d+/
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :account_name, :account_type, :description, :starting_balance
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category_name, :category_type, :color
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :account_id, :amount, :category_id, :cleared, :deleted, :description, :fee, :itemno, :transaction_date
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    begin_date = params[:begin_date]
    end_date = params[:end_date]
    if (!begin_date)
      begin_date = DateTime.now.beginning_of_month
    end
    if (!end_date)
      end_date = begin_date.end_of_month
    end
    @account = Account.find(params[:id])
    @transactions = Transaction.find(:all, :conditions => ["account_id = ? AND transaction_date >= ? AND transaction_date <= ?", params[:id], begin_date, end_date],  :order => "transaction_date, itemno")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
      format.json { render :json => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end
  
  def since
    @account = Account.find(params[:id])
    @transactions = Transaction.find(:all, :conditions => ["account_id = ? AND transaction_date >= ?", params[:id], params[:date]])

    respond_to do |format|
      format.html # since.html.erb
      format.xml  { render :xml => @transactions }
      format.json  { render :json => @transactions }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
	@account_id = params[:id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_name %><br />
    <%= f.text_field :account_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :starting_balance %><br />
    <%= f.text_field :starting_balance %>
  </div>
  <div class="field">
    <%= f.label :account_type %><br />
    <%= f.number_field :account_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Account name</th>
    <th>Description</th>
    <th>Starting balance</th>
    <th>Account type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.account_name %></td>
    <td><%= account.description %></td>
    <td><%= account.starting_balance %></td>
    <td><%= account.account_type %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<br />
<% balance = 0%>
<% @transactions.each do |transaction| %>
<% balance+=transaction.amount.to_f%>
<% end %>
<fieldset>
 <legend class="account"><%=@account.account_name %></legend>
<table align="center" width="90%" cellspacing="0" style="border-style:solid; border-width: 3px; border-color: #3B5998;">
    <tr bgcolor="#3B5998">
		<td colspan=3><br /></td>
		<td colspan=4><h2 style="color:#FFFFFF; font-family: cool_font">Balance: <%=h number_to_currency(balance, :unit => "$")%></h2></td>
    </tr>
	<tr>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="12.5%">Item No.</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="12.5%">Date</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="55%">Description</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="10px">F</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="10px">C</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" >Amount</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" >Balance</th>
	</tr>
<% odd=true%>
<% balance = 0%>
<% @transactions.each do |transaction| %>
<% balance+=transaction.amount.to_f%>
<% if (odd) %>
	<tr bgcolor="#90D8E8" onMouseover="this.bgColor='#FFB200'" onMouseout="this.bgColor='#90D8E8'" onclick="window.location='/transactions/<%=transaction.id%>/edit'">
<% else %>
	<tr bgcolor="#FFFFFF" onMouseover="this.bgColor='#FFB200'" onMouseout="this.bgColor='#FFFFFF'" onClick="window.location='/transactions/<%=transaction.id%>/edit'">
<% end %>
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h transaction.itemno %></td>
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h transaction.transaction_date %></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h transaction.description %></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><input type="checkbox" name="fee" value="<%=h transaction.fee %>"/></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><input type="checkbox" name="fee" value="<%=h transaction.cleared %>"/></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h number_to_currency(transaction.amount, :unit => "$")%></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h number_to_currency(balance, :unit => "$")%></td>
    </tr>
    <% odd = !odd %>
<% end %>
	<tr bgcolor="#BBFF93" onclick="window.location='/transactions/new/<%=@account.id%>'">
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"><br /></td>
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
    </tr>
    <tr bgcolor="#3B5998">
		<td colspan=2 align="left"><h3 style="color:#FFFFFF; font-family: cool_font">&lt;&lt;</h3></td>
		<td colspan=1 align="center">
			<h3 style="color:#FFFFFF; font-family: cool_font">
			&lt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;March&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;
			</h3>
		</td>
		<td colspan=4 align="right"><h3 style="color:#FFFFFF; font-family: cool_font">&gt;&gt;</h3></td>
    </tr>
    </table>
   </fieldset>
 </div>
<%= link_to 'Edit Account', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/since.html.erb
<% balance = 0%>
<% @transactions.each do |transaction| %>
<% balance+=transaction.amount.to_f%>
<% end %>
<fieldset>
 <legend class="account"><%=@account.account_name %></legend>
<table align="center" width="90%" cellspacing="0" style="border-style:solid; border-width: 3px; border-color: #3B5998;">
    <tr bgcolor="#3B5998">
		<td colspan=3><br /></td>
		<td colspan=4><h2 style="color:#FFFFFF; font-family: cool_font">Balance: <%=h number_to_currency(balance, :unit => "$")%></h2></td>
    </tr>
	<tr>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="12.5%">Item No.</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="12.5%">Date</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="55%">Description</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="10px">F</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" width="10px">C</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" >Amount</th>
		<th style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font" >Balance</th>
	</tr>
<% odd=true%>
<% balance = 0%>
<% @transactions.each do |transaction| %>
<% balance+=transaction.amount.to_f%>
<% if (odd) %>
	<tr bgcolor="#90D8E8" onMouseover="this.bgColor='#FFB200'" onMouseout="this.bgColor='#90D8E8'" onclick="window.location='/transactions/<%=transaction.id%>/edit'">
<% else %>
	<tr bgcolor="#FFFFFF" onMouseover="this.bgColor='#FFB200'" onMouseout="this.bgColor='#FFFFFF'" onClick="window.location='/transactions/<%=transaction.id%>/edit'">
<% end %>
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h transaction.itemno %></td>
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h transaction.transaction_date %></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h transaction.description %></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><input type="checkbox" name="fee" value="<%=h transaction.fee %>"/></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><input type="checkbox" name="fee" value="<%=h transaction.cleared %>"/></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h number_to_currency(transaction.amount, :unit => "$")%></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0; font-family: cool_font"><%=h number_to_currency(balance, :unit => "$")%></td>
    </tr>
    <% odd = !odd %>
<% end %>
	<tr bgcolor="#BBFF93" onclick="window.location='/transactions/new/<%=@account.id%>'">
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"><br /></td>
		<td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
	    <td style="border-style:solid; border-width: 1px; border-color: #C0C0C0"></td>
    </tr>
    <tr bgcolor="#3B5998">
		<td colspan=2 align="left"><h3 style="color:#FFFFFF; font-family: cool_font">&lt;&lt;</h3></td>
		<td colspan=1 align="center">
			<h3 style="color:#FFFFFF; font-family: cool_font">
			&lt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;March&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;
			</h3>
		</td>
		<td colspan=4 align="right"><h3 style="color:#FFFFFF; font-family: cool_font">&gt;&gt;</h3></td>
    </tr>
    </table>
   </fieldset>
 </div>
<%= link_to 'Edit Account', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_name %><br />
    <%= f.text_field :category_name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.number_field :color %>
  </div>
  <div class="field">
    <%= f.label :category_type %><br />
    <%= f.number_field :category_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Category name</th>
    <th>Color</th>
    <th>Category type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.category_name %></td>
    <td><%= category.color %></td>
    <td><%= category.category_type %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category name:</b>
  <%= @category.category_name %>
</p>

<p>
  <b>Color:</b>
  <%= @category.color %>
</p>

<p>
  <b>Category type:</b>
  <%= @category.category_type %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/accounts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Accounts: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <style type="text/css">

html { height: 100%; font-size: 62.5% }

/* ==================== Form style sheet ==================== */

form { margin: 25px 0 0 29px; width: 450px; padding-bottom: 30px; }

fieldset {
	margin: 0 0 22px 0; border: 1px solid #3B5998; padding: 12px 17px; background-color: #D8DFEA;
	font-family: cool_font;
	-moz-box-shadow: 3px 3px 4px #000;
	-webkit-box-shadow: 3px 3px 4px #000;
	box-shadow: 3px 3px 4px #000;
	/* For IE 8 */
	-ms-filter: "progid:DXImageTransform.Microsoft.Shadow(Strength=4, Direction=135, Color='#000000')";
	/* For IE 5.5 - 7 */
	filter: progid:DXImageTransform.Microsoft.Shadow(Strength=4, Direction=135, Color='#000000');
}
legend.account { font-size: 2em; background-color: #3B5998; color: #FFFFFF; font-weight: bold; padding: 4px 8px; }
legend { font-size: 1.1em; background-color: #3B5998; color: #FFFFFF; font-weight: bold; padding: 4px 8px; }

label.float { float: left; display: block; width: 100px; margin: 4px 0 0 0; clear: left; font-family: cool_font;}
label { display: block; width: auto; margin: 0 0 10px 0; }
label.spam-protection { display: inline; width: auto; margin: 0; }

input.inp-text, textarea, input.choose, input.answer { border: 1px solid #909090; padding: 3px; }
input.inp-text { width: 300px; margin: 0 0 8px 0; }
textarea { width: 400px; height: 150px; margin: 0 0 12px 0; display: block; }

input.choose { margin: 10px 10px 10px 0; }
input.answer { width: 40px; margin: 0 0 0 10px; }
input.submit-button { font: 1.4em Georgia, "Times New Roman", Times, serif; letter-spacing: 1px; display: block; margin: 23px 0 0 0; }

form br { display: none; }

/* ==================== Form style sheet END ==================== */

</style>
</head>
<body>
	<table width="100%" border=0>
		<tr bgcolor="#3B5998">
			<td colspan=2 align="left"><h1 style="font-size: 3.5em; color: #fff; font-family: cool_font;">Checkbook Pro</h1></td>
		</tr>
		<tr valign="top">
			<td width=20%>
				<div bgcolor="#fff" style="background-color: #fff; border-width: 10px; border-style: solid; border-color: #fff; border-radius: 15px;">
					   <fieldset>
						<legend>Login:</legend>
					    <label for="username" class="float"><strong>User:</strong></label><br />
    					<input type="text" name="username" id="username" class="inp-text"/>
    					<label for="password" class="float"><strong>Password:</strong></label><br />
    					<input type="text" name="password" id="password" class="inp-text"/>
    					<input type="submit" value="Login" class="submit-button"/>
    				</fieldset>
				</div>
			</td>
			<td>
				<div style="color: green"><%= flash[:notice] %></div>
				<%= yield  %>
			</td>
		</tr>
	</table>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkbookproweb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Account</th>
    <th>Description</th>
    <th>Itemno</th>
    <th>Transaction date</th>
    <th>Fee</th>
    <th>Cleared</th>
    <th>Amount</th>
    <th>Category</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.account_id %></td>
    <td><%= transaction.description %></td>
    <td><%= transaction.itemno %></td>
    <td><%= transaction.transaction_date %></td>
    <td><%= transaction.fee %></td>
    <td><%= transaction.cleared %></td>
    <td><%= transaction.amount %></td>
    <td><%= transaction.category_id %></td>
    <td><%= transaction.deleted %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Account:</b>
  <%= @transaction.account_id %>
</p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>

<p>
  <b>Itemno:</b>
  <%= @transaction.itemno %>
</p>

<p>
  <b>Transaction date:</b>
  <%= @transaction.transaction_date %>
</p>

<p>
  <b>Fee:</b>
  <%= @transaction.fee %>
</p>

<p>
  <b>Cleared:</b>
  <%= @transaction.cleared %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>

<p>
  <b>Category:</b>
  <%= @transaction.category_id %>
</p>

<p>
  <b>Deleted:</b>
  <%= @transaction.deleted %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>